GET https://fso-exercises-p3.fly.dev/api/persons

###
GET https://fso-exercises-p3.fly.dev/api/persons/1

###
GET https://fso-exercises-p3.fly.dev/api/persons/32

###
GET https://fso-exercises-p3.fly.dev/info