POST https://fso-exercises-p3.fly.dev/api/persons
content-type: application/json

{
    "name": "Alejandro Pérez",
    "number": "123 456 789"
}

###
POST https://fso-exercises-p3.fly.dev/api/persons
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "123 456 789"
}

###
POST https://fso-exercises-p3.fly.dev/api/persons
content-type: application/json

{
    "number": "123 456 789"
}